# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.0'

gem 'faraday', '~> 2.12'
gem 'faraday-typhoeus', '~> 1.1'
gem 'typhoeus', '~> 1.4', '>= 1.4.1'

group :test, :development do
  gem 'rubocop', '~> 1.66', '>= 1.66.1'
end
